### ISSUE TITLE
Flairs for Articles/MadeWith

### ISSUE THREAD

**Issue by jamesb93** [flucoma/learn-website#104]
https://github.com/flucoma/learn-website/issues/96#issuecomment-990874916

Jacob proposes a great idea to have flairs to help distinguish interviews/articles and what not. This should be relatively easy to implement in the frontmatter by simply adding another variable:

---
flair: podcast
---

or whatever.... then having the layouts render these as it needs.

**Comment by jdchart** [comment]
I'll add to this for myself so not to forget:

- padding needed for contents (hugs the main text when too long)
- padding needed for audio file labels + centre text)
- audio file label download link: underline and link should not span up to " :"
- table of contents position shoudl be absolute maybe? (so still there when scrolled)
