### ISSUE TITLE
Use `target="_blank"` more sparingly in links

### ISSUE THREAD

**Issue by weefuzzy** [flucoma/learn-website#167]
At the moment it seems like every link opens a new tab, which is pretty irritating. IMO, only off-site links should do this. Can the inclusion of `target="_blank"` in `<a>` elements be made conditional somehow?

**Comment by jamesb93** [comment]
Yep ths is a behaviour I have internally logged to check.

It _should_ already be the case that internal links open in `_self` and externals open in `_blank`.

Can you @weefuzzy  point me to some outliers so I can see where the code isn't handling this? I've tried to spot some low hanging fruit but they behaved as I wanted and expected them too.

**Comment by weefuzzy** [comment]
Sorry, missed request for follow up: when I look at any of the generated previews, clicking on pretty much *any* link from the top menu, or for references / overviews opens a new tab....

**Comment by jamesb93** [comment]
No probs, ATM I enforce `<base target="_blank">` and specify `_self` where I think it should be. Seems like none of that is working 🥲I'll review a way that the links all play nice in what is likely to amount to a PR.
