### ISSUE TITLE
bonk~ in hayes' max patches

### ISSUE THREAD

**Issue by jamesb93** [flucoma/learn-website#171]
@jdchart it seems you've used a `bonk~` in Hayes' max examples (4th patch "knife"). It's fine but can we flag this somewhere either in the learn or patch itself? Is it essential to have it in the patch and if the answer is yes we need to provide the download links for it or at least point outwards.

**Comment by jdchart** [comment]
I'll add it to the dependencies part of the parent patcher!

**Comment by jamesb93** [comment]
yep good one. Thanks for looking into this.

**Comment by jdchart** [comment]
Ok, just saw that it was already included in the parent patcher. Is it not clear enough?

**Comment by jamesb93** [comment]
To be honest I was skimming for red. If it's mentioned then let's consider the issue dealt with. Sorry for the noise!

**Comment by jdchart** [comment]
No problem
