### ISSUE TITLE
Image Sizes

### ISSUE THREAD

**Issue by jamesb93** [flucoma/learn-website#185]
Some images in the repo are huge:

https://learn.flucoma.org/overviews/nmfmatch/ and https://learn.flucoma.org/overviews/bufnmf for example.

They should be compressed to jpg and also made as bad as possible without sacrificing fidelity.

**Comment by tedmoore** [comment]
i'm working on going through mine!

**Comment by jamesb93** [comment]
Oops! don't commit anything. I already went through anything pre-existing of yours and compressed it. You should be good to just do it on any unmerged content.

**Comment by jamesb93** [comment]
Files changed here:

https://github.com/flucoma/learn-website/commit/9e2ae892bb5660bd2fc0a13508f062439c124952
