### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by jdchart** [flucoma/learn-website#190]
Just noticed at the bottom of pages there's this footer:

Last modified: Thu Jan 27 09 by Jacob
Commit: 982af2
Edit File on GitHub

Is this intentional ? Date and author i can understand but do people really need to know what commit it is...?

**Comment by jamesb93** [comment]
Not necessarily. I see that pattern a lot for documentation type stuff but I potentially agree with you that it might even put people off?

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics (for example).

**Comment by jdchart** [comment]
fair enough. I dont think it would go so far as to put poepl off, i just personnaly found it a bit weird. i guess i never read the footers of websites!

**Comment by jamesb93** [comment]
Less content on the page means less to render, and less to read. Let's remove it and see if anyone cares.
