### ISSUE TITLE
Quarantine Info for Max

### ISSUE THREAD

**Issue by tedmoore** [flucoma/learn-website#198]
On the [installation/max](https://learn.flucoma.org/installation/max) page should I think we offer some information to the user on what to do when they see this. 

<img width="372" alt="Screenshot 2022-02-01 at 17 47 51" src="https://user-images.githubusercontent.com/1531144/152064436-238a1aca-3d65-48ac-bb64-957bf25262bb.png">

**Comment by jamesb93** [comment]
Yeah, let's tag that for beta5 and unassign everyone except myself.

**Comment by jamesb93** [comment]
Solved in https://github.com/flucoma/learn-website/commit/ddb9ea25e7b59e90599a85ea86db0fd40914c67c
