### ISSUE TITLE
headers for the learn platform

### ISSUE THREAD

**Issue by tremblap** [flucoma/learn-website#199]
We discussed, a thread was started, and we need to decide.

 We change the names of the 3 things. Now, this is where we need to agree as it is more controversial:

  1) Learn/ reference / explore

  2) Overviews / References / Projects

  Contenders for item 3: podcasts/stories

**Comment by tremblap** [comment]
As I said in the thread, I love stories but it feels hippie and a bit corporate-coopting strangely… but I could be swayed

**Comment by jdchart** [comment]
I still vote: learn/reference/explore

overviews is too vague for me. projects not good cause not all the podcasts are projects. stories no.

**Comment by tedmoore** [comment]
For the first one, I do like `learn`

For the second one, it seems `reference` is pretty well liked, including by me

For the third one, I actually still like `projects` or maybe `examples`. I'm not bothered by having podcasts fall under either `examples` or `projects`

**Comment by jamesb93** [comment]
my vote is for learn / explore / reference. In that order as well, such that learn and explore are coupled together whenever we mention it and reference being on the end. This could be supported by some clever UI updates and a bit of guard railing for a user entering the platform. I think that this might suggest a better way of approaching all the content that suggests three unique streams, with their own ways of maneouvering around the content.

**Comment by jamesb93** [comment]
Yes you read me right.

**Comment by tremblap** [comment]
this looks better - it would be great that the logo stayed there when the hamburger arrives though

**Comment by tremblap** [comment]
should I put another ticket?

**Comment by jamesb93** [comment]
> this looks better - it would be great that the logo stayed there when the hamburger arrives though

I'm not sure what "this" is. AFAIK nothing has been changed in regards to the top navigation.



> should I put another ticket?

Already a ticket here: https://github.com/flucoma/learn-website/issues/200
