### ISSUE TITLE
top of learn.flucoma.org

### ISSUE THREAD

**Issue by tremblap** [flucoma/learn-website#200]
we talked about the 3 elements and their relative importance

logo (always there, on the left)

3 items (last resource is to hamburger them)

search (always on the right, shrinks as much as possible)

**Comment by tremblap** [comment]
as a thinking space:
http://www.wekinator.org/

**Comment by jdchart** [comment]
???

is the wekinator website here as an example of what NOT to do ?

**Comment by jamesb93** [comment]
I think a search bar should not shrink too much, but I agree on everything else in terms of preferencing behaviour of the UI. On a similar note I think that perhaps the search bar could organise the results for you like this:

https://www.manomano.co.uk/

to help make the experience of navigating through the results tighter.

It should also have a search icon _before_ the input text to help denote that its a search bar and you are using it to search. I have a dream of a UI where it expands when you focus on the field input and collapses when youre not. I'd have to see how it looks on mobile.
