### ISSUE TITLE
[Bug] TOC parses up to an asterisk 

### ISSUE THREAD

**Issue by jdchart** [flucoma/learn-website#214]
Just noticed this:

![bug](https://user-images.githubusercontent.com/48985961/153606745-b1ceac8e-15d1-4d87-b830-08710210e9d3.png)

**Comment by jdchart** [comment]
i've always wanted to know why is a

**Comment by jamesb93** [comment]
lol

i think that's because it doesn't parse * in the markdown correctly at build time with the scripts.

I'll look into it.

**Comment by jamesb93** [comment]
I actually don't see the TOC at all on the production site 🙃
