### ISSUE TITLE
[Bug] Related + TOC exceeds screen

### ISSUE THREAD

**Issue by jdchart** [flucoma/learn-website#215]
![Capture d’écran 2022-02-11 à 16 33 34](https://user-images.githubusercontent.com/48985961/153620745-1ccec5ec-a929-4f4e-b14d-8bef190c4291.png)

**Comment by jdchart** [comment]
I suppose two independent scroll spaces

**Comment by jamesb93** [comment]
I think it is okay but maybe it could stick better to the top.
