### ISSUE TITLE
strange header

### ISSUE THREAD

**Issue by tremblap** [flucoma/learn-website#217]
This is strange at the top - and I'm pretty sure it wasn't like that before...
![Screenshot 2022-02-13 at 15 00 19](https://user-images.githubusercontent.com/10000381/153759251-2ecf9839-af84-4b5a-a4db-466e76c65319.jpg)

**Comment by jamesb93** [comment]
thanks this is defs broken since I had to accomodate the new tralingSlash changes in SvelteKit 267. I'll fix accordingly.

**Comment by jamesb93** [comment]
Fixed in https://github.com/flucoma/learn-website/commit/bdbe9749414c1d3125dca010402abfbcffdd6c4e
