### ISSUE TITLE
Nicol-LoopE-M.wav should be replaced with drums-m.mp3

### ISSUE THREAD

**Issue by jamesb93** [flucoma/learn-website#225]

**Comment by tremblap** [comment]
If we do so,  we need to give credits somewhere.

**Comment by jamesb93** [comment]
Would you be okay with more web friendly names and a proper list of a credits in the source?

**Comment by jamesb93** [comment]
I've updated this in 7c64361508f741243dd5d6b8495232d1be8ec48b so that all assets use the canonical names from the packages.
