### ISSUE TITLE
adding dequanrantine instructions to install for Pd on mac

### ISSUE THREAD

**Issue by tremblap** [flucoma/learn-website#237]
like Max for Mac

**Comment by tremblap** [comment]
that would be nice. can @tedmoore @jamesb93 or @jdchart do it simply or is it convoluted? Also, maybe we should have a few pictures in step #2 (which should be split in 2 maybe so people put it where they want then add it to the search path? they cannot just drop the folder in the External folder as it is one step too nested...)

**Comment by jamesb93** [comment]
This is solved now in https://github.com/flucoma/learn-website/pull/293
