### ISSUE TITLE
error in the frame formula in 'seeding' article

### ISSUE THREAD

**Issue by tremblap** [flucoma/learn-website#242]
I think we need to make a 'where is my data' explainer as the sentence:

> Also, for seeding, this activation buffer must be [(number of frames in source / hop size) + 1]
in https://learn.flucoma.org/learn/seeding-nmf/
is not always true. It is true in padding mode 0 or 2 depending of overlap. I am happy to explain the various modes and the expected location of time series in descriptor series (including activations and bufstft)

**Comment by tedmoore** [comment]
Because BufNMF doesn't currently have a padding option, this is is closed if / until that option appears.
