### ISSUE TITLE
Install in the search bar doesn't return...

### ISSUE THREAD

**Issue by tremblap** [flucoma/learn-website#256]
https://learn.flucoma.org/installation/

which lead to an interesting aggressive feedback email from someone who didn't see the info there nor in the read me...

that would be great that users searching for insta.... found this right away. anyway to curate that behaviour, maestro @jamesb93 ?

**Comment by jamesb93** [comment]
Can you fwd me the e-mail? It feels a bit client/server to be meeting the demands of users, albeit somewhat justified, by writing more code without engaging them.

**Comment by jamesb93** [comment]
Anyway...

https://github.com/flucoma/learn-website/pull/257
