### ISSUE TITLE
Learn Overview: "Thinking about Statistics"

### ISSUE THREAD

**Issue by tedmoore** [flucoma/learn-website#267]
But probably with a better name. 

It would be good to highlight for users some things to keep in mind as they're looking at the statistics of their buffers. This page, suggested by @tremblap, would be a good place to get ideas from.

https://www.geckoboard.com/best-practice/statistical-fallacies/

**Comment by jamesb93** [comment]
@tedmoore am I right in thinking that the https://github.com/flucoma/learn-website/pull/271 spirit quest will solve this issue?

**Comment by tedmoore** [comment]
Yes, with the caveat that *this* part of #271 is not completed yet, it's more of the "statistical assumptions" page which is not yet complete. I've sort of paused / deferred to @weefuzzy if he has any opinions (or anyone) on what this looks like. If the answer is "no", then I can just take a whack at it and push.
