### ISSUE TITLE
SpectralShape Reference Page not working on Firefox

### ISSUE THREAD

**Issue by tedmoore** [flucoma/learn-website#329]
The audio playback GUI and graphic doesn't work.

**Comment by jamesb93** [comment]
yay 🤡 🤡 🤡 🤡 🤡 🤡

Thanks for reporting.

Do you have a version @tedmoore ?

**Comment by tedmoore** [comment]
version of firefox? no--it was on alice's computer

**Comment by jamesb93** [comment]
> version of firefox? no--it was on alice's computer

If it's an old version I'm unwilling to track it down but I'll try recreate on a newer version.

**Comment by tedmoore** [comment]
Yeah, I mean if it's working on the *current* version of Firefox, I say we can just close this!

**Comment by jamesb93** [comment]
This is actually a problem in latest Firefox which requires a bit of head scratching...

**Comment by tedmoore** [comment]
bummer

**Comment by jamesb93** [comment]
I think I am trying to push the widget too far. It is too kitchen sinky, which would be better as a patch anyway. My idea would be too modify the example to be static and only somewhat interactable while still expressing the various differences you can experience with spectralshape. I shall think..

**Comment by jamesb93** [comment]
I believe this is fixed now!
