### ISSUE TITLE
Change of Heading in KDTree reference

### ISSUE THREAD

**Issue by tedmoore** [flucoma/learn-website#335]
I was clicking around today and saw this. It seems a bit misleading to me. I think something better would be 

`When might a KDTree not be faster than a brute force search?`
or
`Why a KDTree isn't always faster than a brute force search`

The "only sometimes" makes it sound like it is *often* not as fast as a brute force search which leaves the wrong impression.

Thoughts?

<img width="1680" alt="Screenshot 2022-06-13 at 16 24 56" src="https://user-images.githubusercontent.com/1531144/173388680-95702f71-1a51-4b39-9875-cb2253f84263.png">

**Comment by jamesb93** [comment]
We should be wary of overpromising anything and be mindful that KDTree lookups are conveniently fast and nice to play with in our workshop scenarios where its 2 dimensions but are prone to slowness in high-dimensional space.

That said, I just did some armchair warrior research and found this:


https://jakevdp.github.io/blog/2013/04/29/benchmarking-nearest-neighbor-searches-in-python/

So even in quite large spaces (larger than what one would presumably concoct out of FluCoMa) brute force is beaten by the KDTree.

In any case, I am actually inclined to move this tidbit into a `<Pointer type="warning"/>`. What do you think @tedmoore ?

**Comment by tedmoore** [comment]
> We should be wary of overpromising anything and be mindful that KDTree lookups are conveniently fast and nice to play with in our workshop scenarios where its 2 dimensions but are prone to slowness in high-dimensional space.

I agree. The suggested titles are more specific by indicating that the paragraph will explain "when" or "why" this is the case, rather than "sometimes", which depending on the frame of reference might sound like over, or under, promising.

Also, I think it's ok to suggest that the KDTree will "often" be faster than brute force. That's what it's for. Along side the word "often" we should definitely have a bit of information about "when" or "why" that wouldn't be the case.

> In any case, I am actually inclined to move this tidbit into a <Pointer type="warning"/>. What do you think @tedmoore ?

"Warning" seems a bit much. I think it's fine as a header. It is a full paragraph.

**Comment by jamesb93** [comment]
I opted for this:

`Why a Kdtree Is Not Always Faster Than a Brute Force Search`

Given some space to not think about this, I came back to it just then and I think it's just the clearest.

Thanks.

b14b803
