### ISSUE TITLE
old video (pre beta7) linked in article

### ISSUE THREAD

**Issue by tedmoore** [flucoma/learn-website#355]
The [Eldridge-Kiefer article](https://learn.flucoma.org/explore/eldridge-kiefer/) has the old (pre beta7) video embedded. My guess is we should check around for other old videos too (or perhaps just make the old ones "private" instead of "unlisted" on YouTube so that they'll show a 404 and we'll be alerted to any we missed?).

Also I saw a few places in this article that says MLP Regressor where I think it would be great to [link to the page](https://learn.flucoma.org/reference/mlpregressor/)!

<img width="1045" alt="Screenshot 2022-07-24 at 19 09 39" src="https://user-images.githubusercontent.com/1531144/180660242-d1d2c74d-61e8-4078-9704-70ada9931939.png">

**Comment by jdchart** [comment]
well seen! I shall do a pass through them today

**Comment by jamesb93** [comment]
I think the easiest way is to find/replace the video code. Rather than scrubbing through all those pages manually :)

**Comment by jdchart** [comment]
i did a search and replace in all files in vs code. i felt like rami malek in mr robot
