### ISSUE TITLE
Lauren Hayes example patches

### ISSUE THREAD

**Issue by Rhodions** [flucoma/learn-website#363]
Hi
The patches to accompany your articles don't appear to be there. 

Would you be able to update the links? 

Best
Jess Aslan

**Comment by Rhodions** [comment]
<img width="295" alt="Screenshot 2022-08-02 at 13 25 11" src="https://user-images.githubusercontent.com/63867520/182374000-95cd49c3-368b-4ed0-99b1-342adf444e3e.png">

**Comment by jamesb93** [comment]
Hey @Rhodions,

I'm actually solving this as we speak :)

**Comment by Rhodions** [comment]
Yep i'll try now


Dr Jess Aslan

Music and Music Technology
Kingston University
Goldsmiths College, UoL

Dept of Music | 26/1 Laurie Grove | 020 7919 7728

Please note I am a fractional member of staff and my working days are Wednesday – Friday.
________________________________

**Comment by jamesb93** [comment]
Hi @Rhodions. My contract ends in less than a month and I'm looking at cleaning up as many issues as I can before that. Would you be able to confirm its working or not at some point?
