### ISSUE TITLE
mlp-training Max code errors

### ISSUE THREAD

**Issue by jamesb93** [flucoma/learn-website#376]
![image](https://user-images.githubusercontent.com/13281862/184623448-3756241b-012d-4afb-87c2-a8ff165fc3f5.png)

Is all I get when I import the example from the Max tab which doesn't work because there is no data.

@tedmoore would you be able to finish this patch?

**Comment by tedmoore** [comment]
Where is this patch from? What do you mean no data?

**Comment by jamesb93** [comment]
If you copy this patch out this is what you get:

https://github.com/flucoma/learn-website/blob/8b9afa80be263b8a5a901b7843c1899661a54ff4/src/routes/learn/mlp-training.svx#L164

**Comment by tedmoore** [comment]
this is broken because it's pre-beta7. i can fix it and re-upload

this isn't meant to be a whole patch. more like a snippet to demonstrate one way of training with a lower `maxIter` and a `[qmetro]`.

**Comment by jamesb93** [comment]
> this is broken because it's pre-beta7. i can fix it and re-upload
> 
> this isn't meant to be a whole patch. more like a snippet to demonstrate one way of training with a lower `maxIter` and a `[qmetro]`.

Ah I see, though the SuperCollider example generates data to work with so it feels like the parity is not really kept.

**Comment by tedmoore** [comment]
ah good catch. 

do you think max should be updated to be a whole patch as well, or should they both be snippets? i think snippets are ok to have around, not everything needs to be full on, but for this one the SC already exists... so ?
