### ISSUE TITLE
BufScale `clipping` demonstration

### ISSUE THREAD

**Issue by tedmoore** [flucoma/learn-website#378]
In the BufScale web reference https://learn.flucoma.org/reference/bufscale/ the clipping parameter is presented as a checkbox, presumably either true or false, however in the actual implementation of the BufScale object, the parameter is an integer 0-3 that specifies different types of clipping.

(bottom screen shot taken from: https://github.com/flucoma/flucoma-docs/blob/main/doc/BufScale.rst)

![Screenshot 2022-08-16 at 15 09 41](https://user-images.githubusercontent.com/1531144/184900709-83fb7961-dc78-448a-960b-cc5ce4881e28.png)

----------------------------------------------------------------------------------

![Screenshot 2022-08-16 at 15 10 46](https://user-images.githubusercontent.com/1531144/184900943-c542e22b-2fd0-446f-83d9-080cf1154b08.png)

**Comment by jamesb93** [comment]
Very true! I can fix this at some point easily. Cheers for pointing it out.

**Comment by jamesb93** [comment]
I should get around to this soon.

**Comment by jamesb93** [comment]
Fixed in 6c15a25ad3dac058a097ae7bd52f9d06fc9d80d5!
