### ISSUE TITLE
Richard Devine example patch: 02 Number of Slices

### ISSUE THREAD

**Issue by santaluciar** [flucoma/learn-website#392]
The patch mentioned in the object, downloadable in the section explore/devine is broken because the functions of the [js treshfinder.js] has other names than the ones used inside this specific patch.  Cheers

**Comment by jamesb93** [comment]
@tremblap I think that was your abstraction right. I think we need to dig it out of the `git` history and put it back in the package if there are resources that depend on it.

**Comment by jamesb93** [comment]
For now you can drop this into your max Library folder to have access to the missing dependency.
[threshfinder.js.zip](https://github.com/flucoma/learn-website/files/10913934/threshfinder.js.zip)

**Comment by jamesb93** [comment]
I've provided this now with the .zip, so it should work.
