### ISSUE TITLE
NoveltyFeature page - plot is mentionned but non-existent

### ISSUE THREAD

**Issue by tremblap** [flucoma/learn-website#403]

**Comment by jamesb93** [comment]
My best guess is that it was put there with the best intentions but never got completed, or was actually called something else in the end. I have a low confidence suspicion that maybe it got garbled in some `git`ing too, but not sure. Nonetheless the data for a plot is actually there (under `src/lib/data/reference/noveltyfeature/data.json`) and a corresponding and complete example is available for OnsetFeature, so it's not too hard for me, or anyone who would like to to complete.

**Comment by jamesb93** [comment]
Added in 0d9c9e7975c58f014511de6ddad6233d8b17eff5.
