### ISSUE TITLE
Feature Request: Update README.md build instructions

### ISSUE THREAD

**Issue by tedmoore** [flucoma/learn-website#435]
### Is your feature request related to a problem? Please describe the problem.

I would like to contribute to this project but don't know how to build locally so I can test it. It looks like the instructions in the README.md file are generic Svelte instructions, maybe the instructions in the default Svelte project?

What steps do I need to take to build this locally to test my changes?

### Describe the solution you'd like to see.

n/a

### Describe alternatives you've considered

n/a

### Additional context

na/

**Comment by jamesb93** [comment]
I've updated them!
