### ISSUE TITLE
Olivier Pasquet Made with FluCoMa article

### ISSUE THREAD

**Issue by jamesb93** [flucoma/learn-website#96]
In relation to a long e-mail thread here are the condensed improvements that should be at least considered for the current [Olivier Pasquet made with FluCoMa article](learn.flucoma.org/madewithflucoma/pasquet).

1. End of bio of Pasquet, link with pop-up to a website for more information. I don’t want to read more there, but should I want this is where I want it as a reader.

2. I downloaded the zip, and there is a folder called _DeletedItems in there. I reckon it is a mistake?

3. Remove `bach` externals from distributed project and instead point to package manager. Perhaps find if there is a way to make a button that brings up the package manager from max? I reckon something like `max packagemanager` or something probably exists undocumented.

4. Create links to HCMF, to FluCoMa gig on the website 

5. Speakers -> loudspeakers

6. Sound example is long (30sec to illustrate a texture is long - I would put a few seconds before to show the block contrast too)... Ok but let’s start it before the said texture (2 sec) to give the example of the contrast talked about.

7. As with all the “Made with FluCoMa” articles (add the “”, make a link to the series header (people might arrive from google) and link the download to the words ‘downloaded’ later so people don’t have to go at the top if they need it)

8. Ok now I get excited - as soon as you are talking about the 4 ways he takes sounds, I wonder why I cannot see hear them, but then you point at the patch! We should maybe put a warning that when we select a sound it’ll take time to compute and to be patient (or use the @blocking with a timer!) also the already selected sound in the umenu is confusing (I usually use a —select-a-sound— first menu item)

9. `@blocking 0` where possible

10. (The patch keeps on getting dirty (wanting to save) as we use it. We should manage that too)

11. The section on llll is confusing. I would remove 
"Here it suffices to know that an llll is a list that can be given several dimensions (lists within lists); and that in Max, lllls can be referred to with an address. In this instance, Pasquet doesn’t actually use the bach library for its hierarchical possibilities, but as a dynamic way of storing and querying data (note that this can be achieved with the fluid.dataset~ object, however Pasquet used this format to incorporate the data into his own bespoke objects and workflow).”

And replace by

Here it suffices to know that Pasquet uses Bach as a dynamic way of storing and querying data.

Which focuses on the right thing - if people ask why not fluid.dataset we can put a footnote saying that it didn’t exist at the time :) or maybe in the conclusion, reinforcing the strength of the tool (integrating, not replacing, a toolset of a creative coder)

12. LZW should be introduced with parentheses the first time.

**Comment by jdchart** [comment]
- End of bio pop-up website link.

James I believe you added this in another branch ?

**Comment by jamesb93** [comment]
Yep it is in e044c3994682e437139b8d4d22a04f5c7884426b on the #94 PR/branch

**Comment by jdchart** [comment]
- Sound example is long (30sec to illustrate a texture is long - I would put a few seconds before to show the block contrast too)... Ok but let’s start it before the said texture (2 sec) to give the example of the contrast talked about.

The thing with this is that the file was actually one of the outputs that Pasquet inserted into his patch derived from the generative patches. 
I could replace with an extract from the actual performance then.

**Comment by jdchart** [comment]
- Create links to HCMF, to FluCoMa gig on the website

Heads up i've now created an article in madewithflucoma presenting the Rective Flows gig with videos, links to Angela, info on venue etc. Will do the same for Liminal Spaces.

Note: it may be useful to have "flairs" like on reddit for the various things: (article, event, podcast) each with a colour that is clearly visible on the listing in index.

**Comment by jamesb93** [comment]
https://github.com/flucoma/learn-website/issues/104

Such a good idea. I'm on board. Can I assign it to you to do after the hayes article? It will be easier to do it afterwards on a feature branch that we can look at together.

**Comment by jdchart** [comment]
> #104
> 
> Such a good idea. I'm on board. Can I assign it to you to do after the hayes article? It will be easier to do it afterwards on a feature branch that we can look at together.

Happy to!
